
# jsp ì¬ì©

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix= .jsp

#oracle
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/xe
spring.datasource.username=c##sample
spring.datasource.password=1234

server.port=8070

#mapper.xml 위치 : resource 폴더안에 mapper 폴더 생성
mybatis.mapper-locations=classpath:/mapper/**/*.xml

#cool sms 문자인증 key
coolsms.apikey = NCS59JQNDELNIXJG
coolsms.apisecret = PMRGLFAJY8MKHQJ0DUZN8MG37WNXH06R
#보내는 폰 번호
coolsms.fromnumber = 01093085092
coolsms.url = http://api.coolsms.co.kr


